# Generated by Django 5.0.6 on 2024-07-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(blank=True, choices=[('author', 'Author'), ('editor', 'Editor'), ('subscriber', 'Subscriber')], max_length=50, null=True),
        ),
    ]
