# Generated by Django 5.0.6 on 2024-07-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('author', 'Author'), ('editor', 'Editor'), ('subscriber', 'Subscriber')], default='subscriber', max_length=50),
        ),
    ]
