# Generated by Django 5.0.6 on 2024-07-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_profile_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_edit_post', 'Can edit post'), ('can_delete_post', 'Can delete post'), ('can_add_post', 'Can add post')]},
        ),
    ]
