# Generated by Django 5.0.6 on 2024-07-22 10:27

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_created_date_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=blog.models.get_today),
        ),
    ]
